version: '3.8'

services:
  db:
    image: postgres:17.6-alpine
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
